{{- if .Values.image.canaryTag }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}-canary
  labels:
    app: {{ include "api.name" . }}
    track: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "api.name" . }}
      track: canary
  template:
    metadata:
      labels:
        app: {{ include "api.name" . }}
        track: canary
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.canaryTag }}"
          ports:
            - containerPort: 8000
{{- end }}
