replicaCount: 1

image:
  repository: ghcr.io/adiforstudy/cloud-native-platform
  tag: v0.1.1
  canaryTag: ""
  pullPolicy: Always

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

hpa:
  minReplicas: 1
  maxReplicas: 5
  cpuTarget: 50

imagePullSecrets:
  - name: ghcr-secret
