name: CI - Build, Scan, Lint, Push

on:
  push:
    branches: ["main"]
    tags:
      - "v*.*.*"

concurrency:
  group: cd-main
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Sync
      - name: Sync main branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull --rebase origin main

      # Lint
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/Dockerfile

      # QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Version
      - name: Set version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "VERSION=dev-${GITHUB_SHA::7}" >> $GITHUB_ENV
          fi

      # Build local
      - name: Build image (local)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          load: true
          tags: |
            ghcr.io/adiforstudy/cloud-native-platform:latest
            ghcr.io/adiforstudy/cloud-native-platform:${{ env.VERSION }}

      # Trivy
      - name: Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ghcr.io/adiforstudy/cloud-native-platform:latest
          severity: HIGH,CRITICAL
          exit-code: 1
          ignore-unfixed: true
          trivyignores: .trivyignore

      # Helm
      - name: Helm lint
        run: helm lint charts/api

      # Push image
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/adiforstudy/cloud-native-platform:latest
            ghcr.io/adiforstudy/cloud-native-platform:${{ env.VERSION }}

      # Promote dev
      - name: Update dev environment
        run: |
          sed -i "s/^[[:space:]]*tag:.*/  tag: $VERSION/" environments/dev/values.yaml

      - name: Commit dev promotion
        run: |
          git config user.name "github-actions"
          git config user.email "ci@github.com"
          git add environments/dev/values.yaml
          git commit -m "ci: promote $VERSION to dev" || echo "No changes"
          git push origin main


  promote-stage:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update stage values
        run: |
          sed -i "s/^[[:space:]]*tag:.*/  tag: $VERSION/" environments/stage/values.yaml

      - name: Commit stage promotion
        run: |
          git config user.name "github-actions"
          git config user.email "ci@github.com"
          git add environments/stage/values.yaml
          git commit -m "ci: promote $VERSION to stage" || echo "No changes"
          git push
